In [1]:
# Import the Libraries 
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import os

In [2]:
# Load Data Set 
os.chdir('C:\\Users\\nikhil reddy\\Downloads\\Day20\\Day20\\')
dataset = pd.read_csv('Wine.csv')
dataset

Alcohol  Malic_Acid   Ash  Ash_Alcanity  Magnesium  Total_Phenols  \
0      14.23        1.71  2.43          15.6        127           2.80   
1      13.20        1.78  2.14          11.2        100           2.65   
2      13.16        2.36  2.67          18.6        101           2.80   
3      14.37        1.95  2.50          16.8        113           3.85   
4      13.24        2.59  2.87          21.0        118           2.80   
..       ...         ...   ...           ...        ...            ...   
173    13.71        5.65  2.45          20.5         95           1.68   
174    13.40        3.91  2.48          23.0        102           1.80   
175    13.27        4.28  2.26          20.0        120           1.59   
176    13.17        2.59  2.37          20.0        120           1.65   
177    14.13        4.10  2.74          24.5         96           2.05   

     Flavanoids  Nonflavanoid_Phenols  Proanthocyanins  Color_Intensity   Hue  \
0          3.06                  0.28             2.29             5.64  1.04   
1          2.76                  0.26             1.28             4.38  1.05   
2          3.24                  0.30             2.81             5.68  1.03   
3          3.49                  0.24             2.18             7.80  0.86   
4          2.69                  0.39             1.82             4.32  1.04   
..          ...                   ...              ...              ...   ...   
173        0.61                  0.52             1.06             7.70  0.64   
174        0.75                  0.43             1.41             7.30  0.70   
175        0.69                  0.43             1.35            10.20  0.59   
176        0.68                  0.53             1.46             9.30  0.60   
177        0.76                  0.56             1.35             9.20  0.61   

     OD280  Proline  Customer_Segment  
0     3.92     1065                 1  
1     3.40     1050                 1  
2     3.17     1185                 1  
3     3.45     1480                 1  
4     2.93      735                 1  
..     ...      ...               ...  
173   1.74      740                 3  
174   1.56      750                 3  
175   1.56      835                 3  
176   1.62      840                 3  
177   1.60      560                 3  

[178 rows x 14 columns]

In [6]:
# Create X Variable – Independent Variable 
X = dataset.iloc[:, :-1].values
X
# Create y  Variable – Dependent Variable 
y = dataset.iloc[:, -1].values
y

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3], dtype=int64)

In [7]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [8]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test) 

Applying LDA – Fit and Transform Training Data 

In [9]:
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis as LDA
lda = LDA(n_components = 2)
X_train = lda.fit_transform(X_train, y_train)
X_train

array([[-3.57315552,  1.94018924],
       [-0.85475898, -2.08182977],
       [-0.62173655, -3.06234453],
       [-4.80786412,  2.00638739],
       [ 3.8579759 ,  0.14987256],
       [ 3.59455458,  1.24961706],
       [ 0.53772906, -3.0852704 ],
       [-0.04058577, -2.47312446],
       [-0.99835348, -3.36989668],
       [ 3.74095658,  1.94844242],
       [-3.76035226,  0.82126218],
       [ 0.15106412, -1.86820292],
       [-3.62762899,  2.05460026],
       [ 3.94229781,  2.80328429],
       [-3.33429017,  0.73627798],
       [-3.90206871,  1.03276135],
       [ 3.55835472,  0.18783108],
       [-5.63175281,  2.40524214],
       [ 5.56217254,  0.85694946],
       [-0.23296188, -3.94615581],
       [-5.03141997,  3.23313754],
       [-3.52861651,  0.94605778],
       [ 1.17815662, -2.17294825],
       [-3.58320131,  0.67947364],
       [-5.21649905,  2.41090952],
       [ 3.01647841,  1.24411621],
       [-1.86178658, -0.47484926],
       [-3.93816398, -0.2204059 ],
       [ 1.0836235 ,

In [10]:
X_test = lda.transform(X_test)
X_test

array([[ 3.83960313,  1.54567265],
       [-5.24601727,  1.72358501],
       [ 0.66064228, -3.32231072],
       [ 2.16667061,  1.0147427 ],
       [ 0.16079996, -1.27171643],
       [ 5.31374258, -2.22014536],
       [ 4.78386714,  3.11508054],
       [-5.55863966,  0.88556084],
       [ 1.29772139, -2.40714074],
       [-0.53068371, -2.37759837],
       [-2.36900593,  1.81859204],
       [-5.14502202,  1.88061526],
       [ 5.27947032,  3.32510044],
       [ 2.70452577, -2.61522323],
       [-4.32314426,  2.14569837],
       [ 0.65835601, -4.67751669],
       [ 4.07332713,  1.95266123],
       [ 6.55291385,  4.01098911],
       [-2.40020179, -1.14618328],
       [ 5.14219986,  2.02120623],
       [ 2.46475469, -2.81225673],
       [ 2.5190649 ,  1.07965428],
       [ 1.79798575,  0.47987658],
       [ 1.43423986, -2.41298601],
       [-1.11433225, -0.98310413],
       [-0.28604133, -2.81262488],
       [ 1.21198193, -2.73115246],
       [-0.84900431, -3.34996047],
       [ 1.03105294,

In [11]:
lda.explained_variance_ratio_

array([0.73931691, 0.26068309])