# Dimensionality Reduction  

In [1]:
# Import Libraries 
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
import os

In [2]:
# Load Data Set 
os.chdir('C:\\Users\\nikhil reddy\\Downloads\\Day20\\Day20\\')
df = pd.read_csv('trans_us.csv', index_col = 0, thousands  = ',')
df

1990  1991  1992  1993  \
TB prevalence, all forms (per 100 000 populatio...                           
Afghanistan                                          436   429   422   415   
Albania                                               42    40    41    42   
Algeria                                               45    44    44    43   
American Samoa                                        42    14     4    18   
Andorra                                               39    37    35    33   
...                                                  ...   ...   ...   ...   
Wallis et Futuna                                     126   352    64   174   
West Bank and Gaza                                    55    54    54    52   
Yemen                                                265   261   263   253   
Zambia                                               436   456   494   526   
Zimbabwe                                             409   417   415   419   

                                                    1994  1995  1996  1997  \
TB prevalence, all forms (per 100 000 populatio...                           
Afghanistan                                          407   397   397   387   
Albania                                               42    43    42    44   
Algeria                                               43    42    43    44   
American Samoa                                        17    22     0    25   
Andorra                                               32    30    28    23   
...                                                  ...   ...   ...   ...   
Wallis et Futuna                                     172    93   123   213   
West Bank and Gaza                                    52    50    49    46   
Yemen                                                250   244   233   207   
Zambia                                               556   585   602   626   
Zimbabwe                                             426   439   453   481   

                                                    1998  1999  2000  2001  \
TB prevalence, all forms (per 100 000 populatio...                           
Afghanistan                                          374   373   346   326   
Albania                                               43    42    40    34   
Algeria                                               45    46    48    49   
American Samoa                                        12     8     8     6   
Andorra                                               24    22    20    20   
...                                                  ...   ...   ...   ...   
Wallis et Futuna                                     107   105   103    13   
West Bank and Gaza                                    44    42    40    39   
Yemen                                                194   175   164   154   
Zambia                                               634   657   658   680   
Zimbabwe                                             392   430   479   523   

                                                    2002  2003  2004  2005  \
TB prevalence, all forms (per 100 000 populatio...                           
Afghanistan                                          304   308   283   267   
Albania                                               32    32    29    29   
Algeria                                               50    51    52    53   
American Samoa                                         5     6     9    11   
Andorra                                               21    18    19    18   
...                                                  ...   ...   ...   ...   
Wallis et Futuna                                     275   147    63    57   
West Bank and Gaza                                    37    36    35    33   
Yemen                                                149   146   138   137   
Zambia                                               517   478   468   453   
Zimbabwe                                             571   632   652   

In [3]:
# Update Row and Column Headings 
df.index.names = ['stations']
df.columns.names = ['Years']
df

Years               1990  1991  1992  1993  1994  1995  1996  1997  1998  \
stations                                                                   
Afghanistan          436   429   422   415   407   397   397   387   374   
Albania               42    40    41    42    42    43    42    44    43   
Algeria               45    44    44    43    43    42    43    44    45   
American Samoa        42    14     4    18    17    22     0    25    12   
Andorra               39    37    35    33    32    30    28    23    24   
...                  ...   ...   ...   ...   ...   ...   ...   ...   ...   
Wallis et Futuna     126   352    64   174   172    93   123   213   107   
West Bank and Gaza    55    54    54    52    52    50    49    46    44   
Yemen                265   261   263   253   250   244   233   207   194   
Zambia               436   456   494   526   556   585   602   626   634   
Zimbabwe             409   417   415   419   426   439   453   481   392   

Years               1999  2000  2001  2002  2003  2004  2005  2006  2007  
stations                                                                  
Afghanistan          373   346   326   304   308   283   267   251   238  
Albania               42    40    34    32    32    29    29    26    22  
Algeria               46    48    49    50    51    52    53    55    56  
American Samoa         8     8     6     5     6     9    11     9     5  
Andorra               22    20    20    21    18    19    18    17    19  
...                  ...   ...   ...   ...   ...   ...   ...   ...   ...  
Wallis et Futuna     105   103    13   275   147    63    57    60    25  
West Bank and Gaza    42    40    39    37    36    35    33    32    31  
Yemen                175   164   154   149   146   138   137   135   130  
Zambia               657   658   680   517   478   468   453   422   387  
Zimbabwe             430   479   523   571   632   652   680   699   714  

[207 rows x 18 columns]

In [4]:
# Check for Null Values 
df.isna().sum()

Years
1990    0
1991    0
1992    0
1993    0
1994    0
1995    0
1996    0
1997    0
1998    0
1999    0
2000    0
2001    0
2002    0
2003    0
2004    0
2005    0
2006    0
2007    0
dtype: int64

In [5]:
# Create Model 
from sklearn.decomposition import PCA
pca = PCA(n_components=2)
pca.fit(df)

PCA(n_components=2)

In [6]:
# Create PCA  with two variables 
PCA1 = pca.transform(df)
PCA1

array([[ 7.32215864e+02,  2.03381494e+02],
       [-6.13296510e+02,  4.71597812e+00],
       [-5.69303713e+02, -3.68370510e+01],
       [-7.17082766e+02,  5.46469555e+00],
       [-6.61802241e+02,  1.10377364e+01],
       [ 9.90536338e+02,  2.94243725e+02],
       [-6.18891169e+02, -1.45029279e+01],
       [-7.23656796e+02, -5.37125754e+00],
       [-5.08244158e+02,  6.10397004e+01],
       [-4.54552060e+02, -7.89863744e+01],
       [-7.42575408e+02, -1.37488238e+01],
       [-7.15906806e+02, -5.96921991e+00],
       [-4.10215266e+02, -8.35107570e+01],
       [-5.53237930e+02, -1.37877397e+01],
       [-4.43480516e+02,  7.75855551e+01],
       [ 1.42280060e+03,  2.42722083e+02],
       [-7.47393482e+02, -9.33538066e+00],
       [-4.32631571e+02, -3.96933543e+01],
       [-7.15779552e+02, -8.73209243e+00],
       [-5.65111003e+02,  1.40605932e+01],
       [-2.08237408e+02, -3.16580516e+01],
       [-7.38452782e+02, -1.01653102e+01],
       [ 1.74270925e+03,  5.69448954e+02],
       [ 3.

In [7]:
# Convert output to Data Frame 
PCA2= pd.DataFrame(PCA1)
PCA2.index = df.index
PCA2.columns = ['PC1','PC2']
PCA2.head(50)

PC1         PC2
stations                                         
Afghanistan                732.215864  203.381494
Albania                   -613.296510    4.715978
Algeria                   -569.303713  -36.837051
American Samoa            -717.082766    5.464696
Andorra                   -661.802241   11.037736
Angola                     990.536338  294.243725
Anguilla                  -618.891169  -14.502928
Antigua and Barbuda       -723.656796   -5.371258
Argentina                 -508.244158   61.039700
Armenia                   -454.552060  -78.986374
Australia                 -742.575408  -13.748824
Austria                   -715.906806   -5.969220
Azerbaijan                -410.215266  -83.510757
Bahamas                   -553.237930  -13.787740
Bahrain                   -443.480516   77.585555
Bangladesh                1422.800603  242.722083
Barbados                  -747.393482   -9.335381
Belarus                   -432.631571  -39.693354
Belgium                   -715.779552   -8.732092
Belize                    -565.111003   14.060593
Benin                     -208.237408  -31.658052
Bermuda                   -738.452782  -10.165310
Bhutan                    1742.709249  569.448954
Bolivia                    369.739970  192.500210
Bosnia and Herzegovina    -337.633139  142.997336
Botswana                  1124.623706 -503.640618
Brazil                    -394.477560   60.513236
British Virgin Islands    -679.056460    2.317492
Brunei Darussalam         -418.462708   17.711361
Bulgaria                  -544.874902   -6.043780
Burkina Faso               536.374072 -408.919486
Burundi                   1125.814696 -655.801897
Cambodia                  2538.953258  223.864004
Cameroon                   120.281096  -78.943508
Canada                    -748.125458  -11.062861
Cape Verde                 814.529926  136.122326
Cayman Islands            -739.387791   -9.104772
Central African Republic  1003.717739 -355.104319
Chad                       940.992223 -472.269062
Chile                     -662.228202   21.763156
China                      376.487336  121.359175
Colombia                  -491.294650   30.672246
Comoros                   -222.702045   96.540347
Congo, Rep.                803.678138 -453.276487
Cook Islands              -684.975871    0.804587
Costa Rica                -687.115904    9.091935
Croatia                   -382.173929   72.910116
Cuba                      -699.469036   13.694036
Cyprus                    -731.203770   -4.776154
Czech Republic            -698.079517    2.354928

In [8]:
# Display the variance Percentage  
pca.explained_variance_ratio_

array([0.91808789, 0.060556  ])

# Dimensionality Reduction (Bank Data) 

In [10]:
os.chdir ('C:\\Users\\nikhil reddy\\Downloads\\Day20\\Day20\\')
df= pd.read_csv('Bank Data Dimension Reduction.csv')
df

Index  Interest_Rate  Credit  Gender  Previous  Duration Churn
0        0        17546.0       1     0.0       0.0      48.0    NO
1        1        30085.1       3     1.0       1.0      40.0   YES
2        2        16575.4       0     0.0       1.0      51.0   YES
3        3        20375.4       3     0.0       0.0      23.0   YES
4        4        50576.3       0     0.0       0.0      57.0    NO
..     ...            ...     ...     ...       ...       ...   ...
595    595        47025.0       2     0.0       1.0       NaN   YES
596    596         9672.3       0     0.0       1.0       NaN   YES
597    597        15976.3       0     0.0       1.0       NaN    NO
598    598        14711.8       0     1.0       0.0      29.0    NO
599    599        26671.6       0     1.0       1.0      38.0   YES

[600 rows x 7 columns]

In [12]:
# Data Checks 
df.isna().sum()

Index             0
Interest_Rate    68
Credit            0
Gender           21
Previous          7
Duration         70
Churn             0
dtype: int64

In [13]:
df.notna().sum()

Index            600
Interest_Rate    532
Credit           600
Gender           579
Previous         593
Duration         530
Churn            600
dtype: int64

In [14]:
# Data Types 
df.dtypes

Index              int64
Interest_Rate    float64
Credit             int64
Gender           float64
Previous         float64
Duration         float64
Churn             object
dtype: object

In [15]:
df.groupby('Gender').size()

Gender
0.0    290
1.0    289
dtype: int64

In [16]:
df['Gender'] = df['Gender'].fillna(0)
df.groupby('Gender').size()

Gender
0.0    311
1.0    289
dtype: int64

In [17]:
df.groupby('Previous').size()
df['Previous'] = df['Previous'].fillna(0)

In [18]:
df['Interest_Rate'].fillna(df['Interest_Rate'].mean(),inplace = True)

In [19]:
df['Duration'].fillna(df['Duration'].median(),inplace = True)

In [20]:
df['Gender'] = df['Gender']. astype('category')
df.dtypes

Index               int64
Interest_Rate     float64
Credit              int64
Gender           category
Previous          float64
Duration          float64
Churn              object
dtype: object

In [22]:
df['Previous'] = df['Previous']. astype('category')
df.dtypes

Index               int64
Interest_Rate     float64
Credit              int64
Gender           category
Previous         category
Duration          float64
Churn              object
dtype: object

In [23]:
df.dtypes
df['Churn'] = df['Churn']. astype('category')
df['Churn'] = df['Churn'].cat.codes

In [24]:
x = df.iloc[:,1:6].values
x

array([[1.75460e+04, 1.00000e+00, 0.00000e+00, 0.00000e+00, 4.80000e+01],
       [3.00851e+04, 3.00000e+00, 1.00000e+00, 1.00000e+00, 4.00000e+01],
       [1.65754e+04, 0.00000e+00, 0.00000e+00, 1.00000e+00, 5.10000e+01],
       ...,
       [1.59763e+04, 0.00000e+00, 0.00000e+00, 1.00000e+00, 4.30000e+01],
       [1.47118e+04, 0.00000e+00, 1.00000e+00, 0.00000e+00, 2.90000e+01],
       [2.66716e+04, 0.00000e+00, 1.00000e+00, 1.00000e+00, 3.80000e+01]])

In [25]:
y = df.iloc[:,6].values
y

array([0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1,
       1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1,
       0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1,
       0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1,
       1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1,
       0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0,
       1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1,

In [26]:
from sklearn.preprocessing import StandardScaler
sc_x= StandardScaler()
x = sc_x.fit_transform(x)
x

array([[-0.83481117, -0.01104933, -0.96398156, -0.97043679,  0.39357468],
       [ 0.20322955,  1.88312118,  1.03736424,  1.03046381, -0.19900953],
       [-0.91516162, -0.95813458, -0.96398156,  1.03046381,  0.61579376],
       ...,
       [-0.9647577 , -0.95813458, -0.96398156,  1.03046381,  0.02320955],
       [-1.06943845, -0.95813458,  1.03736424, -0.97043679, -1.01381282],
       [-0.07935469, -0.95813458,  1.03736424,  1.03046381, -0.34715558]])

In [27]:
from sklearn.model_selection import train_test_split
x_train,x_test, y_train,y_test = train_test_split(x,y,test_size=0.2)

In [28]:
# Display X Train as Data Frame 
pd.DataFrame(x_train)

0         1         2         3         4
0    7.000182e-01  0.936036  1.037364 -0.970437  1.504670
1   -5.707127e-01 -0.011049  1.037364  1.030464 -0.050863
2   -4.250537e-01 -0.958135  1.037364 -0.970437 -0.050863
3    5.790786e-01 -0.958135 -0.963982  1.030464  1.504670
4   -5.170519e-01 -0.958135  1.037364 -0.970437 -1.236032
..            ...       ...       ...       ...       ...
475  2.108173e-15  0.936036  1.037364  1.030464 -0.643448
476 -7.554790e-01 -0.958135 -0.963982  1.030464  0.023210
477 -8.348112e-01 -0.011049 -0.963982 -0.970437  0.393575
478 -1.925457e-01  0.936036 -0.963982  1.030464  0.023210
479 -9.231006e-01 -0.958135  1.037364  1.030464 -0.569375

[480 rows x 5 columns]

Apply PCA model in x_train and x_test 
 n_components = None ( Maximum Slicing , Slicing based on number of variable in this case maximum slicing is 5 – Number of Independent variables)


In [29]:
from sklearn.decomposition import PCA
pca = PCA(n_components = None)
x_train = pca.fit_transform( x_train)
x_test = pca.transform(x_test)

In [30]:
# Display X Train as Data Frame 
pd.DataFrame(x_train)

0         1         2         3         4
0    1.252791 -0.271759 -0.395380  1.834003 -0.646214
1   -0.284596 -0.915802  1.129052 -0.116708 -0.480384
2   -0.771602 -1.187579 -0.929955  0.453482 -0.265615
3    1.647773 -0.107198 -0.356557 -1.545474 -0.568514
4   -1.639782 -1.107792 -0.671480  0.373080  0.495772
..        ...       ...       ...       ...       ...
475 -0.198742 -0.376691  1.682696  0.494933  0.291109
476 -0.262474  0.110213  0.099679 -1.798721 -0.483822
477 -0.444337  0.955435 -1.028932 -0.085979 -0.782681
478  0.323835  1.173343  1.021691 -0.579011 -0.178906
479 -0.978329 -1.409500  0.784477 -0.765581 -0.321542

[480 rows x 5 columns]

In [31]:
# PCA Percentage
pca.explained_variance_ratio_

array([0.35929426, 0.20421718, 0.18969834, 0.18414304, 0.06264718])